### ISSUE TITLE
FxA-37: 2FA

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#22]
Setup a prototype

**Comment by TDA** [comment]
A _very_ rough requirements doc for 2FA that Shane and I drew up last summer: https://github.com/TDA/2fa/blob/master/Software%20Requirements%20Specification%20-%202FA.docx

(Yes, I know its a .docx on github :(, but that was the only way I would have found it)

**Comment by davismtl** [comment]
Flow I just ran into that I thought I would share here. I was logging into iCloud.com and got a desktop pop-up asking me if I was logging into iCloud from Mountain View (with pic of little map). When I said yes, it presented me with this:
https://docs.google.com/document/d/1Gcq-5oWNGX5mQPKU8-Lipq8QVNfMTTZtfIbFLkkO71I/edit

**Comment by davismtl** [comment]
Putting this here since it was an interesting read on 2FA and is worth consideration: https://www.wired.com/2016/06/hey-stop-using-texts-two-factor-authentication/

**Comment by TDA** [comment]
@davismtl While it is true that GAuth/otherTOTPApps are more secure than traditional SMS, we also need to take into account the number of people who might not have access to (or simply not want to have the overhead of using) a smartphone/app. SMS is accessible and easy to understand and use for most people. If we are absolutely sure that all our users will have access to an app, then yes, but if not, we might need to consider other traditional methods like SMS and email (email might be a not very 2FA-ish option, but we do already have the infra to use it).

Personally, I _always_ use SMS authentication for my gmail, cuz I no longer have the phone I used to set up GAuth for that account, and am too lazy to re-do it on another phone.

**Comment by seanmonstar** [comment]
> email might be a not very 2FA-ish option, but we do already have the infra to use it

We might forget sometimes, but **Signin Confirmation essentially is 2FA** using email, in production right now.

**Comment by davismtl** [comment]
@TDA I totally agree. I was thinking that there could maybe be another way. For example, could we use Firefox for Android to be the mobile app rather than Authenticator. We could just push a notification to the app as a 2nd factor. Perhaps this has different issues but I am just thinking of other ways to do 2FA.

@seanmonstar You are totally right! It is precisely for this reason that we never prioritized this feature in Q3. 

In the context of this feature, 2FA is meant to represent the traditional version with codes generated on another device. We have not prioritized this and probably won't work on it in the next quarter but I like to keep adding documentation (like this article) to the feature cards for future considerations. This is a great place to post relevant articles and content on features we are considering for the future.

**Comment by seanmonstar** [comment]
I've also thought that sending a push notification to Firefox for Android/iOS might be a nice way. Requires that users setup their second device, but then, maybe that's a little nudge: "Setup FxA on a second device, and be more secure"

**Comment by rfk** [comment]
>  but Signin Confirmation essentially is 2FA using email, in production right now.

I agree right now.  But we are about to start exploring ways to avoid the sign-in confirmation flow for some users some of the time, which starts to walk it further away from being 2FA-like, since part of the security story of 2FA is that you opt yourself into doing it all the time.

**Comment by davismtl** [comment]
closing this since we have totp
