### ISSUE TITLE
Mobile Push Pt2: SMS install link

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#53]
- After email confirmation, offer to send app by sms
- Prepopulate email address with deeplink

Continuation of work done here in phase 1: https://waffle.io/mozilla/fxa-features/cards/5820a9739ca711d4005a5408

Feature doc in progress here: https://docs.google.com/document/d/133_Cu0TlWQZIw-ihMH1s-U_80I12MXZcvHQEuFhWbPg/edit#heading=h.xqe7ug4a1vlv

**Comment by rfk** [comment]
I chatted with Travis about this briefly in Hawaii.  He's going to look into preferred SMS vendor and get back to me, and he mentioned two requirements for PII handling etc:

* Make it hard (or preferably impossible) to send an SMS with the address of someone else's account in it.  We should be able to do this because we're sending from a post-verification screen, but it'll require some thought.
* Don't include the email address in plaintext in the link.  We could e.g. obfuscate it behind an opaque token of some sort.

FWIW he was also like "why don't you just send a token that lets them login directly rather than only sending the email, that would be a much nicer user experience" and I pointed out that this is only the first of many phases to explore here...

**Comment by davismtl** [comment]
Good to hear others are thinking about the token too. :)

Let me know what providers he recommends. I'll resume discussions with legal when I'm back next week but I expect it to be slow going with holidays around the corner.

**Comment by davismtl** [comment]
There is just missing the hypothetical implementation plan.  @shane-tomlinson Please take a look at that section.

Thanks

**Comment by davismtl** [comment]
from mtg:
- @ryanfeeley will add missing screenshots of following screens
- @shane-tomlinson looking into providers

**Comment by davismtl** [comment]
from mtg:
- @ryanfeeley hasn't added screenshots. Will do
- @shane-tomlinson  identified the provider for test
- legal (Brian) said NO update required to TOS

**Comment by davismtl** [comment]
@ryanfeeley you also need to find to somewhere to put this in the sms page: 

"SMS service available to U.S. phone numbers only. SMS & data rates may apply. The intended recipient of the email or SMS must have consented."

**Comment by shane-tomlinson** [comment]
> legal (Brian) said NO update required to TOS

I had a look at the section Brian mentioned in email, this section does *not* appear in *our* TOS or PP text. We need to ask Brian if we need it to be added, and if so, that updated text needs to be sent to the legal translators.

**Comment by rfk** [comment]
from mtg:
* => building
* @davismtl following up on final TOS details

**Comment by ryanfeeley** [comment]
@davismtl Met yesterday with Shane and realized that we designed these screens at our work week! I had forgotten. He has it working already.

**Comment by davismtl** [comment]
@ryanfeeley great! Make sure they're in the feature document (link in first comment).

Also, make sure to add the SMS legal message mentioned in other comment above.

**Comment by ryanfeeley** [comment]
@shane-tomlinson I can't find my mockups! Did I actually do them or did you build based on hand-drawn mockups? When time, please paste in doc?

**Comment by jbuck** [comment]
Do we have an idea of the expected volume of text messages we'll be sending using this feature? I'm not sure which number I should be using from https://app.datadoghq.com/dash/234347/fxa-content---connect-another-device?live=true

**Comment by davismtl** [comment]
from mtg: 
- successful look completed in dev
- metric definition was moved to Active

**Comment by davismtl** [comment]
from mtg:
- merged and will be behind a feature flag for train 81
- @shane-tomlinson  is going to document a test plan
- @rfk to reach out to softvision to get this on their radar

**Comment by davismtl** [comment]
from mtg:
- Shane moved feature doc to Github
- Alex added some comments for @shane-tomlinson

**Comment by rfk** [comment]
It's shipping to QA in train-81 \o/

**Comment by davismtl** [comment]
from mtg:
- being QA's
- some improvements coming out in 82
- clean up is happening for 83 so we can roll-out to 5%
- legal sign-off for sms canada, usa, uk.

**Comment by davismtl** [comment]
from mtg:
- going out to 5% (2.5 and 2.5) in train 83
- will be able to measure the control efficiently via an experiment table
- a few issues to review from softvision's feedback about rate limiting 
- feeley discovered that it is displayed to mobile users (moved to Next)

**Comment by davismtl** [comment]
from mtg:
- out at 5% as of this week
- resolved the bug around displaying it to mobile users

**Comment by davismtl** [comment]
- resolved the tracking of installs in train 84 (Adjust params)

**Comment by davismtl** [comment]
from mtg:
- Shane worked on resolving the control since it was not targeting same audience as the experiment (released with 85.3, on April 26th). 
- There is now 10%/10% (since April 20th at 8am EST)
- We do not observer however an increase in traffic per this query: https://sql.telemetry.mozilla.org/queries/4249?p_start_date=2017-04-11&p_end_date=2017-04-24#8483
- Next steps:
  - @rfk will review my query and double check what's up with the traffic.
  - Keep an eye out for metrics now that the improved control is out.
  - Re-do funnel in feature document with updated results

**Comment by rfk** [comment]
> There is now 10%/10% (since April 20th at 8am EST)
> [...]
> @rfk will review my query and double check what's up with the traffic.

I tried viewing the sendSms-related flow events in datadog, but it doesn't look like we've seen any increase since the initial rollout.  Live graph here:

https://app.datadoghq.com/dash/69226/fxa-content---ab-experiments?live=true&page=0&is_auto=false&from_ts=1491010047840&to_ts=1493602047840&tile_size=m&fullscreen=201780215

But here's a redacted snapshot:

![capture](https://cloud.githubusercontent.com/assets/34695/25569868/a64461fe-2e61-11e7-809f-d8273557c80f.PNG)

Which doesn't show any increase in the number of events.  @shane-tomlinson any clue why we don't seem to be observing any increase in volume of these events?

**Comment by rfk** [comment]
@shane-tomlinson points out that we *did* see an increase in the actual sms being sent, see the change in this graph around April 24:

![capture](https://cloud.githubusercontent.com/assets/34695/25612015/7d19e3b0-2f6c-11e7-82b9-10eaa006d341.PNG)

The lack of change in the above datadog graph, may be due to the fact that only 10% of our users report to datadog, and those 10% were all already getting put into the experiment.  Shane says we *should* see an increase in the volume of these events in re:dash, I'm just waiting for the query to update.

**Comment by davismtl** [comment]
Working on refreshing the funnel metrics here: https://docs.google.com/document/d/133_Cu0TlWQZIw-ihMH1s-U_80I12MXZcvHQEuFhWbPg/edit#

**Comment by rfk** [comment]
@philbooth was able to reproduce an increase in traffic in datadog, so it looks like the above concerns were indeed a datadog artifact.

**Comment by davismtl** [comment]
from mtg:

- Alex updating funnel here: https://docs.google.com/document/d/133_Cu0TlWQZIw-ihMH1s-U_80I12MXZcvHQEuFhWbPg/edit#
- Early numbers seem to break even with mobile but drive more installs on desktop. Why? Need to dig in more.
- To-do: break down install rate by OS

**Comment by vladikoff** [comment]
from mtg: If the 500s on the auth-server are nothing to be worried about, @shane-tomlinson can we bump the SMS deployment rate to 50% so push this feature forward?

**Comment by davismtl** [comment]
CARD IS MOVED TO NEW PRODUCT BOARD HERE:

https://projects.growthhackers.com/s2/40eKfejG5z4eIhm2pJE4tQ
